# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

title: To all pickles...
description: > # this means to ignore newlines until "baseurl:"
  The personal site of Tabitha Goodall, freelancer software developer.
  Originally from the UK, currently living in Berlin. Yeah, I'm not a dude, 
  that graphic needs to be changed. 
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

author:
  name: 'Tabitha Goodall'
  email: t.goodall.NOSPAMPLEASE@email.com
  github_username: twitchett
  linkedin_username: tabithagoodall

# Build settings
markdown: kramdown
gems:
  - jekyll-feed
  - jekyll-paginate
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
include: ['_pages']
destination: build

# Site config
paginate: 5
paginate_path: "/blog/page:num/"
