# Site info
title: Tabitha Goodall
description: >
  British-born, Berlin-based freelancer. Writes code for fun and profit.
  Apparently writes blogs now too.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

author:
  name: 'Tabitha Goodall'
  email: t.goodall.NOSPAMPLEASE@email.com
  github_username: twitchett
  linkedin_username: tabithagoodall

# Blog config
permalink: "/blog/:year/:month/:day/:title"
paginate: 5
paginate_path: "/blog/page:num/"
future: true  # display posts with a date in the future
disqus_shortname: twitchett

# Build settings
markdown: kramdown
gems:
  - jekyll-feed
  - jekyll-paginate
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
include: ['_pages']
destination: build
host: 0.0.0.0 # for local dev. gh will override this.

# 3rd party integration
google_analytics: UA-97440732-1
instagram_client_id: 71e0eb821e2e489dbb6bd5e5cb9bc0fa
